// Code generated by go-swagger; DO NOT EDIT.

// Copyright Prometheus Team
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package testable_receiver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostTestReceiversHandlerFunc turns a function with the right signature into a post test receivers handler
type PostTestReceiversHandlerFunc func(PostTestReceiversParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostTestReceiversHandlerFunc) Handle(params PostTestReceiversParams) middleware.Responder {
	return fn(params)
}

// PostTestReceiversHandler interface for that can handle valid post test receivers params
type PostTestReceiversHandler interface {
	Handle(PostTestReceiversParams) middleware.Responder
}

// NewPostTestReceivers creates a new http.Handler for the post test receivers operation
func NewPostTestReceivers(ctx *middleware.Context, handler PostTestReceiversHandler) *PostTestReceivers {
	return &PostTestReceivers{Context: ctx, Handler: handler}
}

/*
	PostTestReceivers swagger:route POST /receivers/test testableReceiver postTestReceivers

Test all receivers (name of notification integrations)
*/
type PostTestReceivers struct {
	Context *middleware.Context
	Handler PostTestReceiversHandler
}

func (o *PostTestReceivers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostTestReceiversParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
