// Code generated by go-swagger; DO NOT EDIT.

// Copyright Prometheus Team
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package testable_receiver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostTestReceiversConfigOKCode is the HTTP code returned for type PostTestReceiversConfigOK
const PostTestReceiversConfigOKCode int = 200

/*
PostTestReceiversConfigOK Successfully tested all receivers from provided configuration file

swagger:response postTestReceiversConfigOK
*/
type PostTestReceiversConfigOK struct {

	/*
	  In: Body
	*/
	Payload *PostTestReceiversConfigOKBody `json:"body,omitempty"`
}

// NewPostTestReceiversConfigOK creates PostTestReceiversConfigOK with default headers values
func NewPostTestReceiversConfigOK() *PostTestReceiversConfigOK {

	return &PostTestReceiversConfigOK{}
}

// WithPayload adds the payload to the post test receivers config o k response
func (o *PostTestReceiversConfigOK) WithPayload(payload *PostTestReceiversConfigOKBody) *PostTestReceiversConfigOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post test receivers config o k response
func (o *PostTestReceiversConfigOK) SetPayload(payload *PostTestReceiversConfigOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTestReceiversConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
