// Code generated by go-swagger; DO NOT EDIT.

// Copyright Prometheus Team
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package testable_receiver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostTestReceiversConfigHandlerFunc turns a function with the right signature into a post test receivers config handler
type PostTestReceiversConfigHandlerFunc func(PostTestReceiversConfigParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostTestReceiversConfigHandlerFunc) Handle(params PostTestReceiversConfigParams) middleware.Responder {
	return fn(params)
}

// PostTestReceiversConfigHandler interface for that can handle valid post test receivers config params
type PostTestReceiversConfigHandler interface {
	Handle(PostTestReceiversConfigParams) middleware.Responder
}

// NewPostTestReceiversConfig creates a new http.Handler for the post test receivers config operation
func NewPostTestReceiversConfig(ctx *middleware.Context, handler PostTestReceiversConfigHandler) *PostTestReceiversConfig {
	return &PostTestReceiversConfig{Context: ctx, Handler: handler}
}

/*
	PostTestReceiversConfig swagger:route POST /receivers/test/config testableReceiver postTestReceiversConfig

Test all receivers (name of notification integrations) from inserted configuration file
*/
type PostTestReceiversConfig struct {
	Context *middleware.Context
	Handler PostTestReceiversConfigHandler
}

func (o *PostTestReceiversConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostTestReceiversConfigParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostTestReceiversConfigOKBodyItems0 post test receivers config o k body items0
//
// swagger:model PostTestReceiversConfigOKBodyItems0
type PostTestReceiversConfigOKBodyItems0 struct {

	// config results
	ConfigResults []*PostTestReceiversConfigOKBodyItems0ConfigResultsItems0 `json:"config-results"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this post test receivers config o k body items0
func (o *PostTestReceiversConfigOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateConfigResults(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostTestReceiversConfigOKBodyItems0) validateConfigResults(formats strfmt.Registry) error {
	if swag.IsZero(o.ConfigResults) { // not required
		return nil
	}

	for i := 0; i < len(o.ConfigResults); i++ {
		if swag.IsZero(o.ConfigResults[i]) { // not required
			continue
		}

		if o.ConfigResults[i] != nil {
			if err := o.ConfigResults[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("config-results" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("config-results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this post test receivers config o k body items0 based on the context it is used
func (o *PostTestReceiversConfigOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateConfigResults(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostTestReceiversConfigOKBodyItems0) contextValidateConfigResults(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.ConfigResults); i++ {

		if o.ConfigResults[i] != nil {
			if err := o.ConfigResults[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("config-results" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("config-results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostTestReceiversConfigOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostTestReceiversConfigOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res PostTestReceiversConfigOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PostTestReceiversConfigOKBodyItems0ConfigResultsItems0 post test receivers config o k body items0 config results items0
//
// swagger:model PostTestReceiversConfigOKBodyItems0ConfigResultsItems0
type PostTestReceiversConfigOKBodyItems0ConfigResultsItems0 struct {

	// error
	Error string `json:"error,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this post test receivers config o k body items0 config results items0
func (o *PostTestReceiversConfigOKBodyItems0ConfigResultsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post test receivers config o k body items0 config results items0 based on context it is used
func (o *PostTestReceiversConfigOKBodyItems0ConfigResultsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostTestReceiversConfigOKBodyItems0ConfigResultsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostTestReceiversConfigOKBodyItems0ConfigResultsItems0) UnmarshalBinary(b []byte) error {
	var res PostTestReceiversConfigOKBodyItems0ConfigResultsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
