// Code generated by go-swagger; DO NOT EDIT.

// Copyright Prometheus Team
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package receiver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/prometheus/alertmanager/api/v2/models"
)

// NewPostTestReceiversParams creates a new PostTestReceiversParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostTestReceiversParams() *PostTestReceiversParams {
	return &PostTestReceiversParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostTestReceiversParamsWithTimeout creates a new PostTestReceiversParams object
// with the ability to set a timeout on a request.
func NewPostTestReceiversParamsWithTimeout(timeout time.Duration) *PostTestReceiversParams {
	return &PostTestReceiversParams{
		timeout: timeout,
	}
}

// NewPostTestReceiversParamsWithContext creates a new PostTestReceiversParams object
// with the ability to set a context for a request.
func NewPostTestReceiversParamsWithContext(ctx context.Context) *PostTestReceiversParams {
	return &PostTestReceiversParams{
		Context: ctx,
	}
}

// NewPostTestReceiversParamsWithHTTPClient creates a new PostTestReceiversParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostTestReceiversParamsWithHTTPClient(client *http.Client) *PostTestReceiversParams {
	return &PostTestReceiversParams{
		HTTPClient: client,
	}
}

/*
PostTestReceiversParams contains all the parameters to send to the API endpoint

	for the post test receivers operation.

	Typically these are written to a http.Request.
*/
type PostTestReceiversParams struct {

	/* Receiver.

	   The receivers to test
	*/
	Receiver *models.Receiver

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post test receivers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostTestReceiversParams) WithDefaults() *PostTestReceiversParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post test receivers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostTestReceiversParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post test receivers params
func (o *PostTestReceiversParams) WithTimeout(timeout time.Duration) *PostTestReceiversParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post test receivers params
func (o *PostTestReceiversParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post test receivers params
func (o *PostTestReceiversParams) WithContext(ctx context.Context) *PostTestReceiversParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post test receivers params
func (o *PostTestReceiversParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post test receivers params
func (o *PostTestReceiversParams) WithHTTPClient(client *http.Client) *PostTestReceiversParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post test receivers params
func (o *PostTestReceiversParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReceiver adds the receiver to the post test receivers params
func (o *PostTestReceiversParams) WithReceiver(receiver *models.Receiver) *PostTestReceiversParams {
	o.SetReceiver(receiver)
	return o
}

// SetReceiver adds the receiver to the post test receivers params
func (o *PostTestReceiversParams) SetReceiver(receiver *models.Receiver) {
	o.Receiver = receiver
}

// WriteToRequest writes these params to a swagger request
func (o *PostTestReceiversParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Receiver != nil {
		if err := r.SetBodyParam(o.Receiver); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
